mod_gradle_script_version=1.0.6

mod_id=imagelib
mod_version=0.0.5
mod_description=A library to load and use custom images from internet

minecraft_version=26.2

fabric_loom_version=1.15-SNAPSHOT
fabric_loader_version=0.18.5
fabric_api_version=0.154.0+26.2

neogradle_version=7.1.38
neoforge_version=26.2.0.7-beta