plugins {
    id 'java-library'
    id 'net.neoforged.gradle.userdev' version "${neogradle_version}"
}

apply from: "https://raw.githubusercontent.com/K1miram/mod-gradle-scripts/${mod_gradle_script_version}/mod.gradle"

apply plugin: 'maven-publish'

publishing {
    publications {
        create("mavenJava", MavenPublication) {
            from components.java
            pom.withXml {
                asNode().dependencies.dependency.each { dep ->
                    assert dep.parent().remove(dep)
                }
            }
        }
    }
}